services:
  models-service:
    build: ./services/models/models-service
    container_name: models-service
    env_file:
      - .env
    ports:
      - "${MODELS_SERVICE__APP__PORT}:8000"
    networks:
      - wideresearcher-network
    depends_on:
      - models-database

  models-database:
    image: postgres:18
    container_name: models-database
    restart: always
    environment:
      POSTGRES_DB: ${MODELS_SERVICE__SQL__DATABASE}
      POSTGRES_USER: ${MODELS_SERVICE__SQL__USER}
      POSTGRES_PASSWORD: ${MODELS_SERVICE__SQL__PASSWORD}
    ports:
      - "${MODELS_SERVICE__SQL__PORT}:5432"
    volumes:
      - models-database-data:/var/lib/postgresql/data
    networks:
      - wideresearcher-network

  models-selector-service:
    build: ./services/models/models-selector-service
    container_name: models-selector-service
    env_file:
      - .env
    ports:
      - "${MODELS_SELECTOR_SERVICE__APP__PORT}:8000"
    networks:
      - wideresearcher-network
    depends_on:
      - models-selector-service-cache

  models-selector-service-cache:
    image: redis:7.2
    container_name: models-selector-service-cache
    restart: always
    ports:
      - "${MODELS_SELECTOR_SERVICE__REDIS__PORT}:6379"
    networks:
      - wideresearcher-network
    command: ["redis-server", "--requirepass", "${MODELS_SELECTOR_SERVICE__REDIS__PASSWORD}"]

  research-service:
    build: ./services/researchers/research-service
    container_name: research-service
    env_file:
      - .env
    ports:
      - "${RESEARCH_SERVICE__APP__PORT}:8000"
    networks:
      - wideresearcher-network
    depends_on:
      - research-cache
      - research-database

  research-cache:
    image: redis:7.2
    container_name: research-cache
    restart: always
    ports:
      - "${RESEARCH_SERVICE__REDIS__PORT}:6379"
    networks:
      - wideresearcher-network
    command: ["redis-server", "--requirepass", "${RESEARCH_SERVICE__REDIS__PASSWORD}"]

  research-database:
    image: mongo:6.0
    container_name: research-database
    restart: always
    ports:
      - "${RESEARCH_SERVICE__MONGO__PORT}:27017"
    networks:
      - wideresearcher-network
    volumes:
      - research-database-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${RESEARCH_SERVICE__MONGO__USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${RESEARCH_SERVICE__MONGO__PASSWORD}
      
  query-generator-service:
    build: ./services/researchers/query-generator-service
    container_name: query-generator-service
    env_file:
      - .env
    ports:
      - "${QUERY_GENERATOR_SERVICE__APP__PORT}:8000"
    networks:
      - wideresearcher-network
    depends_on:
      - query-generator-database

  query-generator-database:
    image: postgres:18
    container_name: sql
    restart: always
    environment:
      POSTGRES_DB: ${QUERY_GENERATOR_SERVICE__SQL__DATABASE}
      POSTGRES_USER: ${QUERY_GENERATOR_SERVICE__SQL__USER}
      POSTGRES_PASSWORD: ${QUERY_GENERATOR_SERVICE__SQL__PASSWORD}
    ports:
      - "${QUERY_GENERATOR_SERVICE__SQL__PORT}:5432"
    volumes:
      - query-generator-database-data:/var/lib/postgresql/data
    networks:
      - wideresearcher-network

networks:
  wideresearcher-network:
    external: true

volumes:
  models-database-data:
  research-database-data:
  query-generator-database-data: