"""empty message

Revision ID: 0ff947975284
Revises: 9ba09ee663f1
Create Date: 2026-04-16 08:57:44.729440

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0ff947975284"
down_revision: Union[str, Sequence[str], None] = "9ba09ee663f1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "page_summaries",
        sa.Column("page_url", sa.Text(), nullable=False),
        sa.Column("research_id", sa.BigInteger(), nullable=False),
        sa.Column("epoch_id", sa.Integer(), nullable=False),
        sa.Column("page_summary", sa.Text(), nullable=False),
        sa.Column("meta_created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("meta_updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["page_url"], ["scrapped_pages.page_url"], name=op.f("fk_page_summaries_page_url_scrapped_pages")
        ),
        sa.ForeignKeyConstraint(
            ["research_id", "epoch_id"],
            ["research_epoches.research_id", "research_epoches.epoch_id"],
            name=op.f("fk_page_summaries_research_id_research_epoches"),
        ),
        sa.ForeignKeyConstraint(
            ["research_id"], ["researches.research_id"], name=op.f("fk_page_summaries_research_id_researches")
        ),
        sa.PrimaryKeyConstraint("page_url", "research_id", "epoch_id", name=op.f("pk_page_summaries")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("page_summaries")
    # ### end Alembic commands ###
